api-version: 1.17
name: TofuTryPlugin
version: 1
main: com.tofu.bean.presentation.Main

commands:
  beans:
    description: beans economy

  jetbean:
    description: bean shoot to location

  spawn:
    description: jet bean to spawn & set

  tofu:
    description: set & de permission