api-version: 1.17
name: TofuTryPlugin
version: 1
main: com.tofu.bean.presentation.Main

commands:
  beans:
    description: beans economy

  jetbean:
    description: bean shoot to location

  beanp:
    description: set permission